name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'javascript_task'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd javascript_task
          if [ ! -f package-lock.json ]; then
            npm install
          else
            npm ci
          fi

      - name: Run lint and tests
        run: |
          cd javascript_task
          npm run lint
          npm test

      - name: Check Prettier formatting
        run: |
          cd javascript_task
          npm run prettier:check
