name: Python Tests

on:
  push:
    branches:
      - main  # Change this if you're using a different branch
  pull_request:
    branches:
      - main  # Run tests on pull requests as well

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]  # Test on multiple Python versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./python_task/requirements.txt ]; then pip install -r ./python_task/requirements.txt; fi

    - name: Run tests
      run: |
        python -m unittest discover -s python_task -p "test_*.py"

    - name: Post results
      if: failure()
      run: |
        echo "Tests failed. See above for details."
